const perMap: any = {
  Acsent: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Bind: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Lotus: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Pearl: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Haven: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Icebox: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Breeze: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Fracture: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Split: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },
}

export default perMap;
