const videoLinks: any = {
  // Make sure to have names with the following format
  // Agentname Map Utility PlaceOnMap Attack/Defence 
  // eg: Kayo Ascent Flashdrive ASite Attack
  // eg: Kayo Ascent Flashdrive ASite Heaven Attack
  // we only want to keep - "A Site Heaven Attack" or "A Site Attack"
  Ascent: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : ["Kayo Ascent Flashdrive BSite Lane Attack", "Kayo Ascent Flashdrive ASite A Main Attack",
            "Kayo Ascent Flashdrive ASite Attack"],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Bind: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Lotus: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Pearl: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Haven: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Icebox: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Breeze: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Fracture: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Split: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },
}

export default videoLinks;