const videoLinks: any = {
  // Make sure to have names with the following format
  // Agentname Map Utility PlaceOnMap Attack/Defence 
  // eg: Kayo Ascent Flashdrive ASite Attack
  // eg: Kayo Ascent Flashdrive ASite Heaven Attack
  // we only want to keep - "A Site Heaven Attack" or "A Site Attack"
  Ascent: {
    Brimstone : {Incendiary:
                [{title: "A Site A Dice Attack from Lobby", id: '4HMIFp4NVM8'},
                {title: "A Site A Dice Attack from Wine", id: 'kw5biVMNKB0'},
                {title: "A Site Bottom Box Attack", id: 'V1VQQxRYUxQ'},
                {title: "A Site Concrete Attack", id: 'cNAh5Yr6h30'},
                {title: "A Site Default Attack from A Main", id: 'xKAzNT3KXDk'},
                {title: "A Site Default Attack from A Main (Fast)", id: 'BbqWDp0fAVA'},
                {title: "A Site Default Attack from Gelato", id: '4IzY1zBcpNo'},
                {title: "A Site Default Attack from Top Mid", id: 'BuHhqskrMSk'},
                {title: "A Site Generator Attack from A Lobby", id: 'hmHyf7QVzlM'},
                {title: "A Site Generator Attack from A Main", id: '0fqEwaY91hM'},
                {title: "A Site Generator Attack from Wine", id: 'FXhbYoVrQ9I'},
                {title: "A Site Heaven Box Attack", id: '1A-83C7QIsI'},
                {title: "A Site A Door Attack", id: 'Ntwx8SBkKuU'},
                {title: "B Site B Default Attack", id: 'a8kflmdcyQ0'},
                {title: "B Site B Corner Attack", id: 'OLX0sWmRZaU'},
                {title: "B Site B Door Attack", id: 'PPazFKu_JrQ'},
                {title: "B Site B Stairs Attack", id: '-KyKrtcGt6c'},],},
    Clove : [],
    Viper : {"Snake Bite": 
            [{title: "A Site A Default Attack 1", id: 'dhEBcCX1Z5s'},
            {title: "A Site A Default Attack 2", id: 'jFH8Km0v3QU'},
            {title: "A Site A Door Attack", id: 'szXRGud-gFE'},
            {title: "A Site A Heaven Attack", id: 'IClB-NCg_hg'},
            {title: "A Site Dice Attack 1", id: 'Rchkit72SVc'},
            {title: "A Site Dice Attack 2", id: 'pwK57Oyj85E'},
            {title: "A Site Generator Attack 1", id: 'xOu03X8StVM'},
            {title: "A Site Generator Attack 2", id: 'oLmdLvdp0jg'},
            {title: "B Site B Spawn Attack", id: 'Wq0z1gOwSgo'},
            {title: "B Site B Stairs Attack", id: 'gO7IodVZo30'},
            {title: "B Site Market Door Attack", id: 'nH_NefiGrMo'},],
          
            "Poison Cloud":
            [{title: "A Site A Short Defense", id: 'zUIe4A4oO9k'},
            {title: "B Site B Lane One Way Defense", id: 'FBByoDqjBqk'},
            {title: "B Site B Main One Way Defense", id: 'N1YTlJraOlI'},
            {title: "A Site A Default Attack", id: 'IEQlDqqIJUA'},
            {title: "A Site A Heaven Attack", id: 'pX2rqHV-rf0'},
            {title: "B Site B Spawn Attack", id: 'OB-EMXhynBg'},
            {title: "B Site B Default Attack", id: 'vaHylHF6s5A'},],
          
            "Toxic Screen": 
            [{title: "A Site A Site Attack", id: 'ysjoPR7fGeQ'},
            {title: "B Site B Site Attack", id: 'KqiZEa1_a6o'},
            {title: "Middle Middle Middle Attack from A Lobby", id: 'bCymCYvP94g'},]},

    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],

    Breach : {Flashpoint:
             [{title: "B Site B Site Attack", id: 'uKxlgb7x5Cw'},
             {title: "A Site A Main Defense from A Short", id: '1vjUcp-oCos'},],
            
              Aftershock:
             [{title: "B Site Tiles Defense from B Main", id: '_ix38P9IQBU'}]},

    Deadlock : [],
    Chamber : [],
    Gekko : [],

    Kayo : {Flashdrive: 
            [{title: "B Site B Lane Attack", id: 'np7BiyTsh5Q'},
            {title: "A Site A Main Attack", id: '7npQY7tjukY'},
            {title: "A Site A Site Attack", id: 'tKJPMLVZ7pc'},
            {title: "A Site A Main Defense 1", id: '3sQpeTaSNqs'},
            {title: "A Site A Main Defense 2", id: 'K_6ZGdSgcXM'},
            {title: "B Site Boat + Logs Attack", id: '1GjcMfy7_3Y'},
            {title: "B Site Post Plant Boat Attack", id: '9tSBDbHtNzU'},
            {title: "Middle Middle Market Attack", id: 'QL0aWMWDFO4'},
            {title: "A Site A Main Defense Pop Flash", id: 'zleKEbavj_A'},
            {title: "A Site Defense Retake", id: 'TO9A0F_ZhTM'},
            {title: "B Site B Lobby Defense", id: 'XRevs8ZTtT4'},
            {title: "B Site B Main Defense from Site", id: 'm6c38A4TO28'},
            {title: "B Site B Main Defense from Market", id: 'Rn1mQYKOfO4'},
            {title: "B Site B Site Retake", id: '_T1YUEDRSEQ'},
            {title: "Middle Middle Middle Attack", id: 'tGpSCRdoe_Q'},
            {title: "Middle Middle Middle Defense from A Short", id: 'SnyQhDe8HRk'},
            {title: "Middle Middle Middle Defense from Market", id: 'gb_14dB6qho'},
            {title: "Middle Middle Mid Link Defense", id: '_s1_i6-H0IA'},],

            Zeropoint: 
            [{title: "A Site A Main Defense", id: 'W0PbP4s7AKs'},
            {title: "A Site A Main Defense from B", id: 'xWsX5tdDpyQ'},
            {title: "A Site A Site Attack Round Start", id: 'bkueL_eamk4'},
            {title: "A Site A Site Attack", id: '1HSA9LNiE3I'},
            {title: "B Site B Site Attack", id: 'J-co3Cb_FLA'},
            {title: "Middle Middle Market Attack", id: 'kMRfCUUbiOc'}],
            
            Fragment: 
            [{title: "A Site A Door Attack", id: 'WmKsDjJ2GOc'},
            {title: "A Site Generator Attack", id: '98Ki3W1JroY'},
            {title: "B Site B Stairs Attack", id: '5SznRj_gSHI'},],},
            
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Bind: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Lotus: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Pearl: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Haven: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Icebox: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Breeze: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Fracture: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },

  Split: {
    Astra : [],
    Brimstone : [],
    Clove : [],
    Iso : [],
    Jett : [],
    Omen : [],
    Viper : [],
    Yoru : [],
    Sage : [],
    Skye : [],
    Sova : [],
    Breach : [],
    Deadlock : [],
    Chamber : [],
    Gekko : [],
    Kayo : [],
    Neon : [],
    Pheonix : [],
    Raze : [],
    Reyna : [],
    Fade : [],
    Cypher : [],
    Killjoy : [],
  },
}

export default videoLinks;